development:
  clients:
    default:
      database: api_development
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
  options:
test:
  clients:
    default:
      database: api_test
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: <%= ENV['MLAB_DATABASE'] %>
      username: <%= ENV['MLAB_USER'] %>
      password: <%= ENV['MLAB_PASSWORD'] %>
      hosts:
        - <%= ENV['MLAB_HOST'] %>:<%= ENV['MLAB_PORT'] %>
      options:
        connection_timeout: 15
